-- SQL
CREATE TABLE "Projetos" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"UserId"	INTEGER NOT NULL,
	"StatusId"	INTEGER NOT NULL,
	"DataAt"	TEXT NOT NULL,
	"DataUp"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
)


CREATE TABLE "Tarefas" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"ProjectId"	INTEGER NOT NULL,
	"StatusId"	INTEGER NOT NULL,
	"PriorityId"	INTEGER NOT NULL DEFAULT 1,
	"UserId"	INTEGER NOT NULL,
	"DateAt"	TEXT NOT NULL,
	"DateUp"	TEXT NOT NULL,
	"Description"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
	FOREIGN KEY("ProjetoId") REFERENCES "Projetos"("ID")
)


CREATE TABLE "Usuarios" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"TypeId"	INTEGER NOT NULL,
	"DateAt"	TEXT NOT NULL,
	"DateUp"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
)

CREATE TABLE "TarefasHistoricos" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TaskId"	INTEGER NOT NULL,
	"TaskDescription"	TEXT,
	"UserId"	INTEGER NOT NULL,
	"StatusId"	INTEGER NOT NULL,
	"ActionId"	INTEGER NOT NULL,
	"DateAt"	TEXT NOT NULL,
	"Description"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
)