services:
    web:
        container_name: taskflow
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./src/taskflow.API/DataBase:/app/DataBase
        environment:
            - ASPNETCORE_ENVIRONMENT=Development